//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollWarrant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationSecurity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationSecurity()
        {
            this.LegacySecurities = new HashSet<LegacySecurity>();
        }
    
        public string ApplicationId { get; set; }
        public string UserId { get; set; }
        public string RoleId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegacySecurity> LegacySecurities { get; set; }
    }
}
